{% set name = "girder-client" %}
{% set version = "3.0.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "6fcd637686b3a2108fb99ddbbac5b0bd3abd0c736a0d457307822d0b46f4fab8" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - girder-cli = girder_client.cli:main

  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - click >=6.7
    - diskcache
    - requests >=2.4.2
    - requests-toolbelt
    - six

test:
  imports:
    - girder_client

  commands:
    - girder-cli --help

about:
  home: https://girder.readthedocs.org/en/latest/python-client.html
  license: Apache 2.0
  license_family: Apache
  summary: 'Python client for interacting with Girder servers'
  doc_url: https://girder.readthedocs.org/en/latest/python-client.html
  dev_url: https://github.com/girder/girder/tree/master/clients/python

extra:
  recipe-maintainers:
    - pmlandwehr
