{% set name = "girder-client" %}
{% set version = "3.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 95cf73313ec486014d3f26a21e2a407935c835f6b8f9e9f1fca8840765b35258

build:
  noarch: python
  entry_points:
    - girder-cli = girder_client.cli:main

  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - click >=6.7
    - diskcache
    - requests >=2.4.2
    - requests-toolbelt
    - six

test:
  imports:
    - girder_client

  commands:
    - girder-cli --help
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://girder.readthedocs.org/en/latest/python-client.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interacting with Girder servers
  doc_url: https://girder.readthedocs.org/en/latest/python-client.html
  dev_url: https://github.com/girder/girder/tree/master/clients/python

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
