{% set name = "girder-client" %}
{% set version = "3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3725a2f3de509b51533bf13a748969c6f7deeb7445c0f788ec9d6f6b71aacf5

build:
  noarch: python
  entry_points:
    - girder-cli = girder_client.cli:main

  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - click >=6.7
    - diskcache
    - requests >=2.4.2
    - requests-toolbelt
    - six

test:
  imports:
    - girder_client

  commands:
    - girder-cli --help
    - pip check

  requires:
    - pip

about:
  home: https://girder.readthedocs.org/en/latest/python-client.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for interacting with Girder servers
  doc_url: https://girder.readthedocs.org/en/latest/python-client.html
  dev_url: https://github.com/girder/girder/tree/master/clients/python

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
