schema_version: 1

context:
  name: girder-client
  version: "5.0.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 92b756c35a8c612a56d454e1c2ee33272dc5089ea65bc0ea6c76737498ffc6f3

build:
  number: 1
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - girder-cli = girder_client.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >=${{ python_min }}
    - click >=6.7
    - diskcache
    - requests >=2.4.2
    - requests-toolbelt
    - six

tests:
  - python:
      imports:
        - girder_client
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - girder-cli --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python client for interacting with Girder servers
  homepage: https://girder.readthedocs.org/en/latest/python-client.html
  repository: https://github.com/girder/girder/tree/master/clients/python
  documentation: https://girder.readthedocs.org/en/latest/python-client.html

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
