travis:
  secure:
    BINSTAR_TOKEN: VzDWBMvjVK7fieQ4vV9IqtqY/hgI54bHWYO+p3xWZGY0DvC0lik+W7BvOFoXVK2NAmILws5emV/nLpU1KkeKDcDeVIp4WEmH7rfbCsh6aNatSB/GKu0DGaekrGR8e4CaPCyeUnVV3yzG4LwEE4GcZJBvhmIxvQBI8usGiTUSiznjr2vJFV9V2YRiSzRcin4O0raXrJG25gDImKqz/reC/LV92aCkLeZk1IlWyML/bnRW3zeHD4MWQCrffYw35gJ5G6X+KIbUWonzL9J1/KLK61jEouLe2yZ+1oes1JzGGeaCywphTzuD3VFSMqLPxVdl4Fgm9eFM8ka/1JX8MlnRfxCY8uU39+aiphGUyzOG5kfHoE35WXti7nAEazv2pkGuANJHfbqvpHzJWMSP2JNJMUL+INwoRFJiEPp4y3aAL4nVU+T6KTc0M63Z0somb31gIhmT5nA/6V+unitz32vQ3KeXDVSchltZuojvYTtpciqteifPmnJpJMxHyzXjJ+3v6xJJ/MaN0dV0Fpj6J/8cKQLk7cnmyNcFQzjalFewSzxm+N4Z6lZl8xNMHzRtgreqHMtdX9QugHW8ED05Xlss/6YAL/r2xnLtW2I+o7M1Mb6L8Kk5xdp4E+k9XJxoEKbKvXg0bQlm3QnpIHQSA2FO8Mm0DUNVKH1AsHQf2CN4DDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
