travis:
  secure:
    BINSTAR_TOKEN: MYqbLpHgU5YxxJL8I3qepCF+C5f8ZsSaJE41yIAt+MvT8VZiEVydcmVk4BJlVYHxnn87+sfPA3udfE61g4UJgfjAdTD7Q19NvKNlcQdg2MwXKNrZQw3ACwX2Rcx1xBAQXqDooL1Uee4rB9R5K+Ha9wOVAzKA2WeBCjq+PhcA2dSZpCd62v3ppSPwGKXd24UgcOA5dBofZYrl4/dnHEPZW/WcoK05vw9Sdj69fjgRLsftkwat22VkZQOO1uOyqRnDu8HO/Ib/VjegEvmV0ZRUpqb5azqDPobJ4jYrHH6+W5IusE+OrbL+45zKZF+REoDPS2AXLFzIooF8dr2vw5CMiwpMHaUy1KvsrIhnNWKmEA73T5/uv4tBeZi2p5n3kcm/zzXsxI53SP+VawMpulOndgSsHGJH1Ch878WTxHlo4zliSS/K7K916eFsm7z6cieE+MsdDr6lSpAEnibwiC74QpaXGu42Q+XA4nYZrRDFtVN2ggHbgaJ6wc+wTp5JN8Ed+V85tyqRNimErBpRZFkcePwdEThVcFRZX4XaqljqO+2+iwPzZ4XDE/X7vmdjsFFscHJEpwxHB1F36tV3ApYa8yUbPrN28Q7p0KedefXP3Swmct63B8ke6EPU/0Bwcdv8BFKoaxsr8ogQtskd8er8COFN3Y4JyI8v8UZkjJkVjCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
